# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.0.3"
  python_check_max: "3.14"
  cov_fail_under: "100"

package:
  name: annotated-doc
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/a/annotated-doc/annotated_doc-${{ version }}.tar.gz
    sha256: e18370014c70187422c33e945053ff4c286f453a984eba84d0dbfa0c935adeda

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.9.1,<0.10.0
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: annotated_doc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source=annotated_doc --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/fastapi/annotated-doc
  summary: Document parameters, class attributes, return types, and variables inline, with Annotated.

extra:
  recipe-maintainers:
    - bollwyvl
